### ISSUE TITLE
Generate AAD Token stage of integration_test does not fail with 404 error

### ISSUE THREAD

**Issue by conorbmurphy** [databricks/mlops-stack#11]
I hadn't run both of the bootstrap.py files, which led to my integration tests failing. In the Generate AAD Token step, I got "curl: (22) The requested URL returned error: 404 Not Found" but this step did not fail. The expected behavior would be to fail this step if no AAD token is created

**Comment by smurching** [comment]
@conorbmurphy thanks for filing - I suspect if we add a `set -ex` to the top of the `generate-aad-token.sh` script [here](https://github.com/databricks/mlops-stack/blob/3c284cbc08f12505e1d5f55c8b9b31f0ea80c92e/%7B%7Bcookiecutter.project_name%7D%7D/.github/workflows/scripts/generate-aad-token.sh#L8), such failures would be caught upfront. Would you be able to test that out & send a pull request if it works?

**Comment by arpitjasa-db** [comment]
Closing this issue since as of https://github.com/databricks/mlops-stack/releases/tag/v0.1 we replaced the Generate AAD token script.
