### ISSUE TITLE
Troubleshoot Azure DevOps guide: Issues arise when there's an existing resource group in the same subscription 

### ISSUE THREAD

**Issue by chengyineng38** [databricks/mlops-stack#28]
Problem: I configured my resource group to be `mlops-stack-ado` but there already exists another resource group in the same subscription. 

Fix: I manually changed all resource group names and storage account names to avoid the clash, but Terraform is not happy. I eventually fixed the clashes by running `terraform init -reconfigure` and `terraform init -migrate-state` in: 

1. `databricks-config/staging` 
2. `databricks-config/prod` 
3. `.mlops-setup-scripts/cicd` 

In hindsight, it probably would have been easier to just start the project from scratch, supplying different resource group and storage account names. Hope this helps someone out there!

**Comment by arpitjasa-db** [comment]
Closing this issue since as of https://github.com/databricks/mlops-stack/releases/tag/v0.1 we replaced Terraform.
