### ISSUE TITLE
Troubleshoot AzureOps Guide: grpc: error while marshaling: string field contains invalid UTF-8 

### ISSUE THREAD

**Issue by chengyineng38** [databricks/mlops-stack#29]
**Error**: `Error: rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8` after running `python .mlops-setup-scripts/terraform/bootstrap.py` and being prompted for region. 

**Fix**: this seems to be a problem with Azure CLI and how it interacts with Terraform. Please see [this Terraform GitHub issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/17563) for fixes. 

<img width="744" alt="Screen Shot 2022-11-18 at 6 57 05 AM" src="https://user-images.githubusercontent.com/59850826/202748009-c197e9dd-4ffd-4c97-aace-6e66b8d8251a.png">

**Comment by arpitjasa-db** [comment]
Closing this issue since as of https://github.com/databricks/mlops-stack/releases/tag/v0.1 we replaced Terraform.
