### ISSUE TITLE
Bug: need to lowercase the project name when passing into azurerm_storage_account

### ISSUE THREAD

**Issue by niall-turbitt** [databricks/mlops-stack#38]
Error when bootstrapping Terraform backend setup with `./mlops-setup-scripts/terraform` module where the package name contains capital letters. `azurerm_storage_account` attribute name must only consist of lowercase letters. We should lowercase the project name passed here

![Screenshot 2022-12-20 at 11 35 09](https://user-images.githubusercontent.com/52167569/208657688-b15e3377-4c36-419e-a271-eac5ab699094.png)

**Comment by arpitjasa-db** [comment]
Closing this issue since as of https://github.com/databricks/mlops-stack/releases/tag/v0.1 we replaced Terraform.
