### ISSUE TITLE
Databricks group name conflict

### ISSUE THREAD

**Issue by dougspadotto** [databricks/mlops-stack#73]
When using the same workspace to mimic staging and prod, .mlops-setup-scripts/cicd/main-azure.tf attempts to create 2 groups with the same name, causing an error.

Fix is to make display_name unique for prod and staging.

**Comment by arpitjasa-db** [comment]
Closing this issue since as of https://github.com/databricks/mlops-stack/releases/tag/v0.1 we replaced Terraform.
