### ISSUE TITLE
Unable to deploy ML Resources

### ISSUE THREAD

**Issue by datascientistlin** [databricks/mlops-stack#8]
Hi Team,

I'm following the instrutions to setup a demo MLOPs project using the sample code. For referece, I have successfully completed the steps detailed in

- ML quickstart
- MLOps setup guide

I have a wroking repo with the CICD workflow setup in Github. However, as I started to provision databricks resources following the instruction from **ML resource config guide**. I got the following error from the Terraform CI check.

<img width="1491" alt="image" src="https://user-images.githubusercontent.com/44249807/192226579-8b52f02d-5982-4879-80b3-4310d1919447.png">

I could run `az login` locally fine. Any idea what could be wrong here?

Thanks in advance for any help or tips.

**Comment by smurching** [comment]
@datascientistlin thanks for filing - did you set the `ARM_ACCESS_TOKEN` secret generated by the MLOps setup scripts? It looks like the secret value might be empty based on the output above. The secret value should be in a file called with a name like `"~/.<project-name>-cicd-terraform-secrets.json"`, where `<project-name>` is the name of your project

**Comment by datascientistlin** [comment]
Thanks @smurching , indeed the `ARM_ACCESS_TOKEN` was missing. However, I couldn't find it from the `~/.<project-name>-cicd-terraform-secrets.json` file either. May I know how I could generate this screte? Maybe I missed a step in the instruction?

**Comment by smurching** [comment]
@datascientistlin to confirm, did you run the Terraform bootstrap scripts from the MLOps setup guide (`python .mlops-setup-scripts/terraform/bootstrap.py`)? That's the script that generates the `ARM_ACCESS_TOKEN`

**Comment by datascientistlin** [comment]
@smurching , yes, I had run `.mlops-setup-scripts/terraform/bootstrap.py` and it generated tokens for my databricks workspaces. but `ARM_ACCESS_TOKEN` had not been generated.

**Comment by smurching** [comment]
@datascientistlin sorry for the slow response - would you mind rerunning the  `.mlops-setup-scripts/terraform/bootstrap.py` script and sharing the output of the command? It should be safe (idempotent) to rerun within the same repo, and should print out the path of a file with the `ARM_ACCESS_TOKEN` secret.

In general, we should remove the need to manually set/copy these secrets into CI/CD by leveraging Terraform to store them automatically - happy to follow up on that in more detail & review a pull request to add it, if you or others are interested in that :)

**Comment by arpitjasa-db** [comment]
Closing this issue since as of https://github.com/databricks/mlops-stack/releases/tag/v0.1 we replaced Terraform.
