### ISSUE TITLE
Command line command described in ml-developer-guide-fs.md fails

### ISSUE THREAD

**Issue by edurdevic** [databricks/mlops-stack#84]
The command `pip install -I -r requirements.txt -r test-requirements.txt` described in `ml-developer-guide-fs.md` does not work because the `requirements.txt` and the `test-requirements.txt` are created in different folders.

**Comment by mingyu89** [comment]
@edurdevic Thanks. I'll address it shortly.

**Comment by mingyu89** [comment]
https://github.com/databricks/mlops-stack/pull/85
