### ISSUE TITLE
Feature Store component with Azure DevOps CI/CD is not supported yet

### ISSUE THREAD

**Issue by jackroseman** [databricks/mlops-stack#86]
Creating formal issue to push support for feature store with ADO CI/CD
![image](https://github.com/databricks/mlops-stack/assets/25406312/cee7e7bc-ecf0-492c-99f2-cd761bd03fc2)

**Comment by mingyu89** [comment]
This issue has been addressed by https://github.com/databricks/mlops-stack/pull/91.
