### ISSUE TITLE
 databricks bundle do not use a proxy

### ISSUE THREAD

**Issue by aminebizid** [databricks/mlops-stack#90]
I'm using a proxy in github action runner by setting these env variables

- http_proxy
- https_proxy
- no_proxy
- HTTP_PROXY
- HTTPS_PROXY
- NO_PROXY

I believe that "databricks bundle" command do not use the proxy
I get this error
Error: error downloading Terraform: Get "https://releases.hashicorp.com/terraform/index.json": Forbidden
when running `databricks bundle validate -e test`

**Comment by pietern** [comment]
Was this the same issue as https://github.com/databricks/cli/issues/550?

**Comment by mingyu89** [comment]
Thank you @pietern
